/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Version of the schema, according to Semantic versioning (ISO, https://semver.org/ version 2.0.0 or newer)
 */
export type SchemaVersion = string;
/**
 * The family or primary name(s) of the person addressed in the certificate
 */
export type FamilyName = string;
/**
 * The family name(s) of the person transliterated
 */
export type StandardisedFamilyName = string;
/**
 * The given name(s) of the person addressed in the certificate
 */
export type GivenName = string;
/**
 * The given name(s) of the person transliterated
 */
export type StandardisedGivenName = string;
/**
 * Date of Birth of the person addressed in the DGC. ISO 8601 date format restricted to range 1900-2099
 */
export type DateOfBirth = string;
/**
 * EU eHealthNetwork: Value Sets for Digital Green Certificates. version 1.0, 2021-04-16, section 2.1
 *
 * This interface was referenced by `EUDGC`'s JSON-Schema
 * via the `definition` "disease-agent-targeted".
 */
export type DiseaseAgentTargeted = string;
/**
 * Dose Number / Total doses in Series: positive integer, range: [1,9]
 *
 * This interface was referenced by `EUDGC`'s JSON-Schema
 * via the `definition` "dose_posint".
 */
export type DosePosint = number;
/**
 * Country of Vaccination / Test, ISO 3166 where possible
 *
 * This interface was referenced by `EUDGC`'s JSON-Schema
 * via the `definition` "country_vt".
 */
export type CountryVt = string;
/**
 * Certificate Issuer
 *
 * This interface was referenced by `EUDGC`'s JSON-Schema
 * via the `definition` "issuer".
 */
export type Issuer = string;
/**
 * Certificate Identifier, UVCI
 *
 * This interface was referenced by `EUDGC`'s JSON-Schema
 * via the `definition` "certificate_id".
 */
export type CertificateId = string;
/**
 * EU eHealthNetwork: Value Sets for Digital Green Certificates. version 1.0, 2021-04-16, section 2.2
 *
 * This interface was referenced by `EUDGC`'s JSON-Schema
 * via the `definition` "vaccine-prophylaxis".
 */
export type VaccineProphylaxis = string;
/**
 * EU eHealthNetwork: Value Sets for Digital Green Certificates. version 1.0, 2021-04-16, section 2.3
 *
 * This interface was referenced by `EUDGC`'s JSON-Schema
 * via the `definition` "vaccine-medicinal-product".
 */
export type VaccineMedicinalProduct = string;
/**
 * EU eHealthNetwork: Value Sets for Digital Green Certificates. version 1.0, 2021-04-16, section 2.4
 *
 * This interface was referenced by `EUDGC`'s JSON-Schema
 * via the `definition` "vaccine-mah-manf".
 */
export type VaccineMahManf = string;
/**
 * EU eHealthNetwork: Value Sets for Digital Green Certificates. version 1.0, 2021-04-16, section 2.8
 *
 * This interface was referenced by `EUDGC`'s JSON-Schema
 * via the `definition` "test-manf".
 */
export type TestManf = string;
/**
 * EU eHealthNetwork: Value Sets for Digital Green Certificates. version 1.0, 2021-04-16, section 2.9
 *
 * This interface was referenced by `EUDGC`'s JSON-Schema
 * via the `definition` "test-result".
 */
export type TestResult = string;

/**
 * EU Digital Green Certificate
 */
export interface EUDGC {
  ver: SchemaVersion;
  /**
   * Surname(s), given name(s) - in that order
   */
  nam: {
    fn?: FamilyName;
    fnt: StandardisedFamilyName;
    gn?: GivenName;
    gnt?: StandardisedGivenName;
    [k: string]: unknown;
  };
  dob: DateOfBirth;
  /**
   * Vaccination Group
   */
  v?: [VaccinationEntry, ...VaccinationEntry[]];
  /**
   * Test Group
   */
  t?: [TestEntry, ...TestEntry[]];
  /**
   * Recovery Group
   */
  r?: [RecoveryEntry, ...RecoveryEntry[]];
  [k: string]: unknown;
}
/**
 * Vaccination Entry
 *
 * This interface was referenced by `EUDGC`'s JSON-Schema
 * via the `definition` "vaccination_entry".
 */
export interface VaccinationEntry {
  /**
   * disease or agent targeted
   */
  tg: string;
  /**
   * vaccine or prophylaxis
   */
  vp: string;
  /**
   * vaccine medicinal product
   */
  mp: string;
  /**
   * Marketing Authorization Holder - if no MAH present, then manufacturer
   */
  ma: string;
  /**
   * Dose Number
   */
  dn: number;
  /**
   * Total Series of Doses
   */
  sd: number;
  /**
   * Date of Vaccination
   */
  dt: string;
  /**
   * Country of Vaccination
   */
  co: string;
  /**
   * Certificate Issuer
   */
  is: string;
  /**
   * Unique Certificate Identifier: UVCI
   */
  ci: string;
  [k: string]: unknown;
}
/**
 * Test Entry
 *
 * This interface was referenced by `EUDGC`'s JSON-Schema
 * via the `definition` "test_entry".
 */
export interface TestEntry {
  tg: DiseaseAgentTargeted;
  /**
   * Type of Test
   */
  tt: string;
  /**
   * NAA Test Name
   */
  nm?: string;
  /**
   * RAT Test name and manufacturer
   */
  ma?: string;
  /**
   * Date/Time of Sample Collection
   */
  sc: string;
  /**
   * Date/Time of Test Result
   */
  dr?: string;
  /**
   * Test Result
   */
  tr: string;
  /**
   * Testing Centre
   */
  tc: string;
  /**
   * Country of Test
   */
  co: string;
  /**
   * Certificate Issuer
   */
  is: string;
  /**
   * Unique Certificate Identifier, UVCI
   */
  ci: string;
  [k: string]: unknown;
}
/**
 * Recovery Entry
 *
 * This interface was referenced by `EUDGC`'s JSON-Schema
 * via the `definition` "recovery_entry".
 */
export interface RecoveryEntry {
  tg: DiseaseAgentTargeted;
  /**
   * ISO 8601 Date of First Positive Test Result
   */
  fr: string;
  /**
   * Country of Test
   */
  co: string;
  /**
   * Certificate Issuer
   */
  is: string;
  /**
   * ISO 8601 Date: Certificate Valid From
   */
  df: string;
  /**
   * Certificate Valid Until
   */
  du: string;
  /**
   * Unique Certificate Identifier, UVCI
   */
  ci: string;
  [k: string]: unknown;
}
/**
 * Person name: Surname(s), given name(s) - in that order
 *
 * This interface was referenced by `EUDGC`'s JSON-Schema
 * via the `definition` "person_name".
 */
export interface PersonName {
  fn?: FamilyName;
  fnt: StandardisedFamilyName;
  gn?: GivenName;
  gnt?: StandardisedGivenName;
  [k: string]: unknown;
}
