/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * EU Digital Covid Certificate
 */
export type EUDCC = EUDCC1 & EUDCC2;
/**
 * Version of the schema, according to Semantic versioning (ISO, https://semver.org/ version 2.0.0 or newer)
 */
export type SchemaVersion = string;
/**
 * The surname or primary name(s) of the person addressed in the certificate
 */
export type Surname = string;
/**
 * The surname(s) of the person, transliterated ICAO 9303
 */
export type StandardisedSurname = string;
/**
 * The forename(s) of the person addressed in the certificate
 */
export type Forename = string;
/**
 * The forename(s) of the person, transliterated ICAO 9303
 */
export type StandardisedForename = string;
/**
 * Date of Birth of the person addressed in the DCC. ISO 8601 date format restricted to range 1900-2099 or empty
 */
export type DateOfBirth = string;
/**
 * EU eHealthNetwork: Value Sets for Digital Covid Certificates. version 1.0, 2021-04-16, section 2.1
 */
export type DiseaseAgentTargeted = string;
export type EUDCC2 = {
  [k: string]: unknown;
};

export interface EUDCC1 {
  ver?: SchemaVersion;
  /**
   * Surname(s), forename(s) - in that order
   */
  nam?: {
    fn?: Surname;
    fnt: StandardisedSurname;
    gn?: Forename;
    gnt?: StandardisedForename;
    [k: string]: unknown;
  };
  dob?: DateOfBirth;
  /**
   * Vaccination Group
   */
  v?: [VaccinationEntry];
  /**
   * Test Group
   */
  t?: [TestEntry];
  /**
   * Recovery Group
   */
  r?: [RecoveryEntry];
  [k: string]: unknown;
}
/**
 * Vaccination Entry
 */
export interface VaccinationEntry {
  /**
   * disease or agent targeted
   */
  tg: string;
  /**
   * vaccine or prophylaxis
   */
  vp: string;
  /**
   * vaccine medicinal product
   */
  mp: string;
  /**
   * Marketing Authorization Holder - if no MAH present, then manufacturer
   */
  ma: string;
  /**
   * Dose Number
   */
  dn: number;
  /**
   * Total Series of Doses
   */
  sd: number;
  /**
   * ISO8601 complete date: Date of Vaccination
   */
  dt: string;
  /**
   * Country of Vaccination
   */
  co: string;
  /**
   * Certificate Issuer
   */
  is: string;
  /**
   * Unique Certificate Identifier: UVCI
   */
  ci: string;
  [k: string]: unknown;
}
/**
 * Test Entry
 */
export interface TestEntry {
  tg: DiseaseAgentTargeted;
  /**
   * Type of Test
   */
  tt: string;
  /**
   * NAA Test Name
   */
  nm?: string;
  /**
   * RAT Test name and manufacturer
   */
  ma?: string;
  /**
   * Date/Time of Sample Collection
   */
  sc: string;
  /**
   * Test Result
   */
  tr: string;
  /**
   * Testing Centre
   */
  tc?: string;
  /**
   * Country of Test
   */
  co: string;
  /**
   * Certificate Issuer
   */
  is: string;
  /**
   * Unique Certificate Identifier, UVCI
   */
  ci: string;
  [k: string]: unknown;
}
/**
 * Recovery Entry
 */
export interface RecoveryEntry {
  tg: DiseaseAgentTargeted;
  /**
   * ISO 8601 complete date of first positive NAA test result
   */
  fr: string;
  /**
   * Country of Test
   */
  co: string;
  /**
   * Certificate Issuer
   */
  is: string;
  /**
   * ISO 8601 complete date: Certificate Valid From
   */
  df: string;
  /**
   * ISO 8601 complete date: Certificate Valid Until
   */
  du: string;
  /**
   * Unique Certificate Identifier, UVCI
   */
  ci: string;
  [k: string]: unknown;
}
