/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Version of the schema, according to Semantic versioning (ISO, https://semver.org/ version 2.0.0 or newer)
 */
export type SchemaVersion = string;
/**
 * The family or primary name(s) of the person addressed in the certificate
 */
export type FamilyName = string;
/**
 * The family name(s) of the person transliterated
 */
export type StandardisedFamilyName = string;
/**
 * The given name(s) of the person addressed in the certificate
 */
export type GivenName = string;
/**
 * The given name(s) of the person transliterated
 */
export type StandardisedGivenName = string;
/**
 * Date of Birth of the person addressed in the DGC. ISO 8601 date format restricted to range 1900-2099
 */
export type DateOfBirth = string;
/**
 * EU eHealthNetwork: Value Sets for Digital Green Certificates. version 1.0, 2021-04-16, section 2.1
 */
export type DiseaseAgentTargeted = "840539006";

/**
 * EU Digital Green Certificate
 */
export interface EUDGC {
  ver: SchemaVersion;
  /**
   * Surname(s), given name(s) - in that order
   */
  nam: {
    fn?: FamilyName;
    fnt: StandardisedFamilyName;
    gn?: GivenName;
    gnt?: StandardisedGivenName;
    [k: string]: unknown;
  };
  dob: DateOfBirth;
  /**
   * Vaccination Group
   */
  v?: [VaccinationEntry, ...VaccinationEntry[]];
  /**
   * Test Group
   */
  t?: [TestEntry, ...TestEntry[]];
  /**
   * Recovery Group
   */
  r?: [RecoveryEntry, ...RecoveryEntry[]];
  [k: string]: unknown;
}
/**
 * Vaccination Entry
 */
export interface VaccinationEntry {
  /**
   * disease or agent targeted
   */
  tg: "840539006";
  /**
   * vaccine or prophylaxis
   */
  vp: "1119305005" | "1119349007" | "J07BX03";
  /**
   * vaccine medicinal product
   */
  mp:
    | "EU/1/20/1528"
    | "EU/1/20/1507"
    | "EU/1/21/1529"
    | "EU/1/20/1525"
    | "CVnCoV"
    | "NVX-CoV2373"
    | "Sputnik-V"
    | "Convidecia"
    | "EpiVacCorona"
    | "BBIBP-CorV"
    | "Inactivated-SARS-CoV-2-Vero-Cell"
    | "CoronaVac"
    | "Covaxin";
  /**
   * Marketing Authorization Holder - if no MAH present, then manufacturer
   */
  ma:
    | "ORG-100001699"
    | "ORG-100030215"
    | "ORG-100001417"
    | "ORG-100031184"
    | "ORG-100006270"
    | "ORG-100013793"
    | "ORG-100020693"
    | "ORG-100020693"
    | "ORG-100010771"
    | "ORG-100024420"
    | "ORG-100032020"
    | "Gamaleya-Research-Institute"
    | "Vector-Institute"
    | "Sinovac-Biotech"
    | "Bharat-Biotech";
  /**
   * Dose Number
   */
  dn: number;
  /**
   * Total Series of Doses
   */
  sd: number;
  /**
   * Date of Vaccination
   */
  dt: string;
  /**
   * Country of Vaccination
   */
  co: string;
  /**
   * Certificate Issuer
   */
  is: string;
  /**
   * Unique Certificate Identifier: UVCI
   */
  ci: string;
  [k: string]: unknown;
}
/**
 * Test Entry
 */
export interface TestEntry {
  tg: DiseaseAgentTargeted;
  /**
   * Type of Test
   */
  tt: string;
  /**
   * NAA Test Name
   */
  nm?: string;
  /**
   * RAT Test name and manufacturer
   */
  ma?:
    | "1232"
    | "1304"
    | "1065"
    | "1331"
    | "1484"
    | "1242"
    | "1223"
    | "1173"
    | "1244"
    | "1360"
    | "1363"
    | "1767"
    | "1333"
    | "1268"
    | "1180"
    | "1481"
    | "1162"
    | "1271"
    | "1097"
    | "1489"
    | "344"
    | "345"
    | "1218"
    | "1343";
  /**
   * Date/Time of Sample Collection
   */
  sc: string;
  /**
   * Date/Time of Test Result
   */
  dr?: string;
  /**
   * Test Result
   */
  tr: "260415000" | "260373001";
  /**
   * Testing Centre
   */
  tc: string;
  /**
   * Country of Test
   */
  co: string;
  /**
   * Certificate Issuer
   */
  is: string;
  /**
   * Unique Certificate Identifier, UVCI
   */
  ci: string;
  [k: string]: unknown;
}
/**
 * Recovery Entry
 */
export interface RecoveryEntry {
  tg: DiseaseAgentTargeted;
  /**
   * ISO 8601 Date of First Positive Test Result
   */
  fr: string;
  /**
   * Country of Test
   */
  co: string;
  /**
   * Certificate Issuer
   */
  is: string;
  /**
   * ISO 8601 Date: Certificate Valid From
   */
  df: string;
  /**
   * Certificate Valid Until
   */
  du: string;
  /**
   * Unique Certificate Identifier, UVCI
   */
  ci: string;
  [k: string]: unknown;
}
