name: ci-deploy
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: Version to deploy
jobs:
  deploy:
    runs-on: ubuntu-20.04
    environment: dev
    env:
      APP_VERSION: ${{ github.event.inputs.version }}
    steps:
    - name: cf setup
      run: |-
        curl -sL "https://packages.cloudfoundry.org/stable?release=${CF_RELEASE}&version=${CF_VERSION}" | \
        sudo tar -zx -C /usr/local/bin
      env:
        CF_VERSION: 7.2.0
        CF_RELEASE: linux64-binary
    - name: cf push
      run: |-
        cf api ${CF_API}
        cf auth
        cf target -o ${CF_ORG} -s ${CF_SPACE}
        cf push ${APP_NAME} --docker-image ${APP_IMAGE}:${APP_VERSION} --docker-username ${CF_DOCKER_USERNAME}
      env:
        APP_NAME: dgca-issuance-web
        APP_IMAGE: docker.pkg.github.com/${{ github.repository }}/dgca-issuance-web
        CF_API: ${{ secrets.CF_API }}
        CF_ORG: ${{ secrets.CF_ORG }}
        CF_SPACE: ${{ secrets.CF_SPACE }}
        CF_USERNAME: ${{ secrets.CF_USERNAME }}
        CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
        CF_DOCKER_USERNAME: ${{ secrets.CF_DOCKER_USERNAME }}
        CF_DOCKER_PASSWORD: ${{ secrets.CF_DOCKER_PASSWORD }}
