name: ci-pull-request
on:
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: docker
      run: |-
        docker build . \
        --file ./Dockerfile
